remote_theme: pages-themes/midnight@v0.2.0 # https://github.com/pages-themes/midnight
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: I love her so much
description: the purpose of this site is for me to have so much fun learning things.

markdown: CommonMarkGhPages

show_downloads: true
  # ["true" or "false" (unquoted) to indicate whether to provide a download URL]

- name: Github Pages Directory Listing
  uses: jayanta525/github-pages-directory-listing@v4.0.0
